const dataExp = [
    {
        title: "BRAVO - Công ty phần mềm ERP",
        times: "7/2024 -  nay",
        link: "https://www.bravo.com.vn/",
        usedTech: "- Thiết kế hệ thống dịch vụ cho thuê ERP/SaaS nền tảng Cloud Native với đảm bảo mở rộng theo quy mô, tính bảo mật và tính sẵn sàng, nâng cấp định kỳ theo chuẩn benchmark từ CNCF và Rancher",
        descripttion1: "- Quản trị ~1000 namespace của dự án (mỗi môi trường ~250-300 namespace)",
        descripttion2: "- Viết các ứng dụng Nodejs/Golang làm việc với API các dịch vụ (Argo CD API, Gitlab API, Hashicorp Vault API, Kubeapi-server...) phát triển các tính năng tự động hóa.",
        descripttion3: "- Triển khai và viết quy trình quản trị hệ thống Load balancing, cluster CEPH storage, Logging ELK Stack-Logstash",
        descripttion4: "- Xây dựng luồng CI/CD theo tiêu chuẩn DevSecOps",
        descripttion5: "- Triển khai quy trình cài đặt máy chủ Tuning, Hardening OS Linux, Windows Server hoặc dịch vụ theo tiêu chuẩn Security Benchmark, Performance Benchmark.",
        descripttion6: "- Thiết kế Helmchart ứng dụng theo tiêu chuẩn",
        descripttion7: "- Đề xuất những phương án giải pháp kỹ thuật cho dự án (backup, network, lựa chọn đánh giá máy chủ vật lý, thiết bị mạng)...",
        descripttion4: "- Thiết kế xây dựng luồng Auto HealthCheck dịch vụ Loadbalancing",
        descripttion14:"- Xây dựng quy trình vận hành quản trị hệ thống Kubernetes(phân quyền, audit, policy,...)",
        descripttion9: "- Xử lý sự cố về Kubernetes/RKE2 khi có phát sinh ",
        descripttion8: "- Xây dựng bộ tài liệu quy trình ISO-IEC 27001/9001",
        descripttion9: "- Triển khai hệ thống LDAP Container MSSQL Server trên K8S",
        // descripttion10: "- Quản trị hệ thống Service mesh Istio, update cập nhật network policy theo namespace.",
        // descripttion11: "- Xây dựng hệ thống giám metrics Prometheus/Grafana cập nhật và cảnh báo ứng dụng, và viết Bot Alert",
        // descripttion12: "- Xây dựng source code IaC phục vụ cho vụ việc vận hành làm task và khôi phục hệ thống khi có sự cố",
        line: "",
        position: "Senior Devops Engineer",
    },
    {
        title: "VNPAY",
        times: "10/2022 -  7/2024",
        link: "https://vnpay.vn",
        usedTech: "- Vận hành và quản trị nhiều máy chủ load balacing Nginx+ thực hiện công việc quy trình Scrum/Agile",
        descripttion1: "- Triển khai nhiều cụm cluster Redis, Rabbit MQ ",
        descripttion2: "- Tham gia triển khai cài đặt hệ thống DR (Topup Billing service, OTP service)",
        descripttion3: "- Viết tool cài đặt phần mềm cho nhiều server",
        descripttion4: "- Nghiên cứu xây dựng giải pháp CI/CD Automation áp dụng vận hành, quản trị cho Windows Server AD ",
        descripttion5: "- Nghiên cứu công nghệ OpenTelemetry, Yugabyte Database, Teleport, Fedora CoreOS ",
        // descripttion6: "- Nghiên cứu công nghệ OpenTelemetry, Yugabyte Database, Teleport, Fedora CoreOS ",
        line: "",
        position: "Site Reliability Engineering",
    },
    {
        title: "Isofh",
        times: "2021 - 2022",
        link: "https://isofh.com",
        usedTech: "- Thiết kế vẽ mô hình kiến trúc hệ thống khi có dự án mới  ",
        descripttion:  "- Quản lý và triển khai ứng dụng cho 25 dự án HIS/EMR cho các bệnh viện lớn với lượng request cao trên nền tảng On Premise, bệnh viện vừa và nhỏ trên nền tảng cloud AWS, Sunteco, Vietel Cloud...",
        descripttion2: "- Vận hành server khách hàng, Xây dựng và triển khai giải pháp giám sát hệ thống tập trung ~500 server khách hàng",
        descripttion3: "- Cài đặt, sửa chữa và tối ưu pipeline Jenkins CI/CD cho các dự án đang chạy, và viết các job build cho dự án mới",
        descripttion4: "- Xây dựng hệ thống tự động triển khai hệ thống máy chủ dự án bằng công cụ IaC",
        descripttion6: "- Tuning, Hardening OS tinh chỉnh cấu hình dịch vụ (Load Balancing, Queue, Cache..) các chuẩn Benchmark ",
        descripttion7: "- Tư vấn và chuyển đổi ứng dụng HIS/EMR qua môi trường kubernetes, nâng cấp chuyển đổi CICD sang mô hình GitOps",
        descripttion10:"- Làm Audit ISO-IEC 27001 - 9001 định kỳ các năm ",
        descripttion5: "- Xây dựng hệ thống tự động triển khai hệ thống máy chủ dự án bằng IaC tool",
        descripttion8: "- Lên kế hoạch vận hành bảo trì hệ thống định kỳ, quản trị database PostGresĐB",
        descripttion9: "- Chuyển đổi Haproxy thành Nginx, lên kế hoạch backup",
        line: "4",
        position: "Devops Engineer",
    },
    {
        title: "Terralogic Software",
        times: "2018 - 2021",
        link: "https://terralogic.com",
        usedTech: "",
        descripttion:  "- Quản lý source code server Gitlab Local Server..",
        descripttion2: "- Quản lý và điều hành cụm proxmoxVM, thiết bị storage NAS syslogogy",
        descripttion3: "- Viết các job jenkins thực hiện automation cho việc vận hành và quản trị",
        descripttion4: "- Làm việc với các dịch vụ EC2 , ECS, Glacier , S3 , EFS , EBS , ELB , VPC , CloudWatch , IAM trên cloud AWS bằng IaC Terraform",
        descripttion6: "- Báo cáo, thống kê chi phí sử dụng AWS cho dự án",
        descripttion8: "- Lập kế hoạch mua bán, thanh lý, nâng cấp các thiết bị CNTT trong phòng",
        line: "2",
        position: "Senior System Admin",
    },
    // {
    //     title: "J&T Express",
    //     times: "1/2017 -  7/2020",
    //     link: "https://jtexpress.vn/",
    //     usedTech: "",
    //     descripttion1: "- Thiết kế hệ thống mạng quản trị mạng và serer nội bộ Trụ sở chính ~250 enduser",
    //     descripttion3: "- Quản trị viên văn phòng Active Directory server, Group Policy",
    //     descripttion4: "- Cấu hình switch Cisco Core 9300, switch Access Cisco 9200, HA Tường lửa Fortinet 201E ",
    //     descripttion6: "- Thiết lập và quản trị hệ thống zabbix monitoring, xử lý sự cố mạng văn phòng ",
    //     descripttion7: "- Làm việc với API các dịch vụ VM Promox, Wifi Unify viết các service phục vụ cho công việc báo cáo tài nguyên, thống kê",
    //     descripttion8: "- Xây dựng chính sách, quy trình bảo mật, quản lý thiết bị theo tiêu chuẩn ISO/IEC 27001-9001 ",
    //     line: "2",
    //     position: "System Network Administrator",
    // },
    {
        title: "Công việc khác",
        times: "2024 -  nay",
        link: "https://emso.vn/",
        usedTech: "",
        descripttion: "- Lên kế hoạch phân tách cho ứng dụng Mạng xã hội Emso thành Microservice trên Cloud CMC",
        descripttion1: "- Xây dựng toàn bộ hệ thống kiến trúc về hệ thống cho ứng dụng (quy trình xác thực, log center, monitor center, registry , CICD, Load balancing, Queue cache...) triển khai trên môi trường platform K8s ",
        descripttion2: "- Làm giải pháp tracing hoạt động của API ứng dụng qua Istio",
        descripttion3: "- Code các service trên ngôn ngữ (Javascript, Golang)",
        descripttion4: "- Lên các giải pháp về backup",
        line: "",
        position: "Devops Specialist",
    }

];



export default dataExp;
