const dataExp = [
    {
        title: "VNPAY - Vietnam Payment Joint Stock Company",
        times: "10/2023 -  Present",
        link: "https://vnpay.vn",
        usedTech: "- Operate and administer multiple Nginx plus load balancing High Availability servers (Topup Billing, EFIN projects,... connected to banks)",
        descripttion: "- Deploy, Setup Gitlab CI/CD Ansible solution for nginx plus config, setup newserver",
        descripttion1: "- Participate in building and deploying Disaster Recovery system (Topup Billing service, OTP service)",
        descripttion2: "- Write a tool to automatically install Agent software (nagios, wazuh,...) to serve the installation of multiple servers",
        descripttion3: "- Deploy gitlab CI / Ansible for operate Windows Server (create new record, AD user administration, Firewall management. ",
        descripttion4: "- Operate other server monitoring ",
        line: "",
        position: "System Engineer / SRE ",
    },
    {
        title: "Isofh MedTech Company",
        times: "7/2021 -  10/2023",
        link: "https://isofh.com",
        usedTech: "- Plan new architecture (draw flow activity diagram, architectural connection model of High Availability application)",
        descripttion:  "- Manage and deploy applications for 25 HIS/EMR and Isofhcare, Ivirse projects for large hospitals on the On Premise platform, AWS, Sunteco, Vietel Cloud cloud computing platforms.",
        descripttion1: "- Administer and operate internal VMware Exsi and Vcenter virtualization systems",
        descripttion2: "- Build and deploy system monitoring solutions ~500 server with Prometheus & Grafana technology, Loki Log centralized management.",
        descripttion3: "- Installation, repair and optimization of Jenkins CI/CD for projects, private Dockerhub",
        descripttion4: "- Build Ansible/Gitlab CD system for application administration, application deployment, and environment settings.",
        descripttion5: "- Training, orientation, and motivation to research and study for team members.",
        descripttion6: "- Tuning, Hardening OS Linux (Ubuntu, Redhat), tweaking service configuration (Nginx, Haproxy, Redis, RabbitMQ,..), Install and configure Postgres Database  (Master-Slaves) with Ansible Automation, Operate and administer Jira, Confluence, Gitlab local systems.",
        descripttion7: "- Deploy HIS/EMR applications on k8s environment and Develop CI/CD on GitOps platform (ArgoCD, Gitlab CI, Harbor registry...).",
        descripttion8: "- Write scripts to periodically backup VM, Data, Windows DNS server administrator, integrate authentication of some wifi services, VPN client, Sysnology NAS storage.",
        line: "",
        position: "Senior System Admin / Devops Engineer",
    },
    {
        title: "Terralogic Software",
        times: "07/2020 -  7/2021",
        link: "https://terralogic.com",
        usedTech: "",
        descripttion:  "- Managing source code servers SVN Server, Bitbucket Repository.",
        descripttion2: "- Manage and administer proxmoxVM  cluster, Nas synology",
        descripttion3: "- Deploy writing Jenkins Job (pipeline) to build app for projects",
        descripttion4: "- Support configuration consulting, setup and management of server infrastructure on AWS for the company's outsourcing projects",
        descripttion6: "- Report and statistics on costs of using AWS for projects",
        descripttion7: "- Domain administration, SSL, for projects, project equipment management, office equipment",
        descripttion5: "- Support foreign users",
        descripttion8: "- Plan to buy, sell, liquidate and upgrade IT equipment in the room",
        line: "",
        position: "System Admin",
    },
    {
        title: "J&T Express",
        times: "1/2019 -  7/2020",
        link: "https://jtexpress.vn/",
        usedTech: "",
        descripttion:  "- Network administrator and internal serer Head office 250 users",
        descripttion2: "- Deploy infrastructure office documents, install system wifi controller",
        descripttion3: "- Administrator office Active Directory server, Group Policy ",
        descripttion4: "- Configure Cisco C9200 switch, create Rule, configure site to site Forinet 201E Firewall",
        descripttion6: "- Configure zabbix to monitor device networks, fix network VP errors, and office servers",
        descripttion7: "- Write a website to manage server lists and report server resource statistics",
        descripttion8: "- Create security policies and procedures, manage equipment according to ISO standards ",
        line: "",
        position: "IT Network Administrator",
    },
    // {
    //     title: "Công việc khác",
    //     times: "2015 -  2018",
    //     // link: "https://jtexpress.vn/",
    //     usedTech: "",
    //     descripttion: "- Tư vấn lắp đặt phần cứng, camera giám sát, ổ lưu trữ NAS",
    //     descripttion2: "- Support end user",
    //     descripttion3: "- Develop website outsource",
    //     line: "",
    //     position: "IT",
    // }

];

export default dataExp;
