// const dataExp = [
//     {
//         title: "VNPAY - Vietnam Payment Joint Stock Company",
//         times: "10/2023 -  Present",
//         link: "https://vnpay.vn",
//         usedTech: "- Operate and administer multiple Nginx plus load balancing High Availability servers (Topup Billing, EFIN projects,... connected to banks)",
//         descripttion: "- Deploy, Setup Gitlab CI/CD Ansible solution for nginx plus config, setup newserver",
//         descripttion1: "- Participate in building and deploying Disaster Recovery system (Topup Billing service, OTP service)",
//         descripttion2: "- Write a tool to automatically install Agent software (nagios, wazuh,...) to serve the installation of multiple servers",
//         descripttion3: "- Deploy gitlab CI / Ansible for operate Windows Server (create new record, AD user administration, Firewall management. ",
//         descripttion4: "- Operate other server monitoring ",
//         line: "",
//         position: "System Engineer",
//     },
//     {
//         title: "Isofh MedTech Company",
//         times: "7/2021 -  10/2023",
//         link: "https://isofh.com",
//         usedTech: "- Plan new architecture (draw flow activity diagram, architectural connection model of High Availability application)",
//         descripttion:  "- Manage and deploy applications for 25 HIS/EMR and Isofhcare, Ivirse projects for large hospitals on the On Premise platform, AWS, Sunteco, Vietel Cloud cloud computing platforms.",
//         descripttion1: "- Administer and operate internal VMware Exsi and Vcenter virtualization systems",
//         descripttion2: "- Build and deploy system monitoring solutions ~500 server with Prometheus & Grafana technology, Loki Log centralized management.",
//         descripttion3: "- Installation, repair and optimization of Jenkins CI/CD for projects, private Dockerhub",
//         descripttion4: "- Build Ansible/Gitlab CD system for application administration, application deployment, and environment settings.",
//         descripttion5: "- Training, orientation, and motivation to research and study for team members.",
//         descripttion6: "- Tuning, Hardening OS Linux (Ubuntu, Redhat), tweaking service configuration (Nginx, Haproxy, Redis, RabbitMQ,..), Install and configure Postgres Database  (Master-Slaves) with Ansible Automation, Operate and administer Jira, Confluence, Gitlab local systems.",
//         descripttion7: "- Deploy HIS/EMR applications on k8s environment and Develop CI/CD on GitOps platform (ArgoCD, Gitlab CI, Harbor registry...).",
//         descripttion8: "- Write scripts to periodically backup VM, Data, Windows DNS server administrator, integrate authentication of some wifi services, VPN client, Sysnology NAS storage.",
//         line: "",
//         position: "Devops Engineer",
//     },
//     {
//         title: "Terralogic Software",
//         times: "07/2020 -  7/2021",
//         link: "https://terralogic.com",
//         usedTech: "",
//         descripttion:  "- Managing source code servers SVN Server, Bitbucket Repository.",
//         descripttion2: "- Manage and administer proxmoxVM  cluster, Nas synology",
//         descripttion3: "- Deploy writing Jenkins Job (pipeline) to build app for projects",
//         descripttion4: "- Support configuration consulting, setup and management of server infrastructure on AWS for the company's outsourcing projects",
//         descripttion6: "- Report and statistics on costs of using AWS for projects",
//         descripttion7: "- Domain administration, SSL, for projects, project equipment management, office equipment",
//         descripttion5: "- Support foreign users",
//         descripttion8: "- Plan to buy, sell, liquidate and upgrade IT equipment in the room",
//         line: "",
//         position: "System Admin",
//     },
//     {
//         title: "J&T Express",
//         times: "1/2019 -  7/2020",
//         link: "https://jtexpress.vn/",
//         usedTech: "",
//         descripttion:  "- Network administrator and internal serer Head office 250 users",
//         descripttion2: "- Deploy infrastructure office documents, install system wifi controller",
//         descripttion3: "- Administrator office Active Directory server, Group Policy ",
//         descripttion4: "- Configure Cisco C9200 switch, create Rule, configure site to site Forinet 201E Firewall",
//         descripttion6: "- Configure zabbix to monitor device networks, fix network VP errors, and office servers",
//         descripttion7: "- Write a website to manage server lists and report server resource statistics",
//         descripttion8: "- Create security policies and procedures, manage equipment according to ISO standards ",
//         line: "",
//         position: "IT Network Administrator",
//     },
//     // {
//     //     title: "Công việc khác",
//     //     times: "2015 -  2018",
//     //     // link: "https://jtexpress.vn/",
//     //     usedTech: "",
//     //     descripttion: "- Tư vấn lắp đặt phần cứng, camera giám sát, ổ lưu trữ NAS",
//     //     descripttion2: "- Support end user",
//     //     descripttion3: "- Develop website outsource",
//     //     line: "",
//     //     position: "IT",
//     // }
//
// ];

const dataExp = [
    {
        title: "VNPAY - Công Ty Thanh Toán Việt Nam",
        times: "10/2023 -  Present",
        link: "https://vnpay.vn",
        usedTech: "- Vận hành và quản trị nhiều máy chủ Nginx plus load balacing HA server (Topup billing, EFIN, các kết nối tới bank,....",
        descripttion: "- Triển khai và setup Gitlab CI + Ansible cho deploy config Nginx, Setup cặp server mới",
        descripttion1: "- Tham gia triển khai cài đặt hệ thống DR (Topup Billing service, OTP service)",
        descripttion2: "- Viết tool shell script cài đặt phần mềm monitor (nagios, wazuh,...) cho nhiều server",
        descripttion3: "- Xây dựng giải pháp Gitlab CI / Ansible cho Windows Server AD ",
        line: "",
        position: "System Engineer",
    },
    {
        title: "Isofh MedTech Company",
        times: "7/2021 -  10/2023",
        link: "https://isofh.com",
        usedTech: "- Lên kiến trúc giải pháp sơ đồ luồng hoạt động, mô hình kết nối của ứng dụng có tính sẵn sàng cao ",
        descripttion:  "- Quản lý và triển khai ứng dụng cho 25 dự án HIS/EMR và Isofhcare, Ivirse cho các bệnh viện lớn trên nền tảng On Premise, nền tảng điện toán đám mây AWS, Sunteco, Vietel Cloud.",
        descripttion1: "- Quản trị và vận hành hệ thống ảo hóa VMware Exsi và Vcenter nội bộ",
        descripttion2: "- Xây dựng và triển khai giải pháp giám sát hệ thống ~500 server với công nghệ Prometheus & Grafana, quản lý Log (ELK stack, Loki)",
        descripttion3: "- Cài đặt, sửa chữa và tối ưu Jenkins CI/CD cho các dự án",
        descripttion4: "- Xây dựng hệ thống CD Ansible/Gitlab để quản trị ứng dụng, triển khai ứng dụng và cài đặt môi trường.",
        descripttion5: "- Đào tạo, định hướng, tạo động lực nghiên cứu, học tập cho các thành viên trong nhóm.",
        descripttion6: "- Tuning, Hardening OS Linux (Ubuntu, Centos), tinh chỉnh cấu hình dịch vụ (Nginx, Haproxy, Redis, RabbitMQ,..), Cài đặt và cấu hình Postgres Database (Master-Slaves), Vận hành và quản trị Jira, Confluence, Gitlab local.",
        descripttion7: "- Triển khai các ứng dụng HIS/EMR trên môi trường k8s và Phát triển CI/CD trên nền tảng GitOps (ArgoCD, Gitlab CI, Harbor register...).",
        descripttion8: "- Viết web quản trị máy chủ dự án, thiết lập backup data, backup VM trên Veeam Software",
        line: "",
        position: "Devops Engineer",
    },
    {
        title: "Terralogic Software",
        times: "07/2020 -  7/2021",
        link: "https://terralogic.com",
        usedTech: "",
        descripttion:  "- Quản lý source code server SVN Server, Bitbucket Repository..",
        descripttion2: "- Quản lý và điều hành cụm proxmoxVM, Nas synology",
        descripttion3: "- Triển khai viết Jenkins Job (pipeline) để xây dựng app cho dự án",
        descripttion4: "- Hỗ trợ tư vấn cấu hình, setup và quản lý hạ tầng máy chủ trên AWS cho các dự án outsourcing của công ty",
        descripttion6: "- Báo cáo, thống kê chi phí sử dụng AWS cho dự án",
        descripttion7: "- Quản trị tên miền, SSL, cho dự án, quản lý thiết bị dự án, thiết bị văn phòng",
        descripttion5: "- Hỗ trợ người dùng nước ngoài",
        descripttion8: "- Lập kế hoạch mua bán, thanh lý, nâng cấp các thiết bị CNTT trong phòng",
        line: "",
        position: "System Admin",
    },
    {
        title: "J&T Express",
        times: "1/2019 -  7/2020",
        link: "https://jtexpress.vn/",
        usedTech: "",
        descripttion:  "- Quản trị mạng và serer nội bộ Trụ sở chính 250 người dùng",
        descripttion2: "- Triển khai hạ tầng văn phòng, cài đặt hệ thống điều khiển wifi",
        descripttion3: "- Quản trị viên văn phòng Active Directory server, Group Policy ",
        descripttion4: "- Cấu hình switch Cisco C9200, tạo Rule, cấu hình site to site Forinet 201E Tường lửa",
        descripttion6: "- Cấu hình zabbix để giám sát mạng thiết bị, sửa lỗi VP mạng, máy chủ văn phòng",
        descripttion7: "- Viết website quản lý danh sách server và báo cáo thống kê tài nguyên server",
        descripttion8: "- Xây dựng chính sách, quy trình bảo mật, quản lý thiết bị theo tiêu chuẩn ISO 27000 ",
        line: "",
        position: "IT Administrator",
    },
    // {
    //     title: "Công việc khác",
    //     times: "2015 -  2018",
    //     // link: "https://jtexpress.vn/",
    //     usedTech: "",
    //     descripttion: "- Tư vấn lắp đặt phần cứng, camera giám sát, ổ lưu trữ NAS",
    //     descripttion2: "- Support end user",
    //     descripttion3: "- Develop website outsource",
    //     line: "",
    //     position: "IT",
    // }

];



export default dataExp;
